# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_pb2 as grpc__pb2


class GrpcStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Detect = channel.unary_unary(
        '/Grpc/Detect',
        request_serializer=grpc__pb2.Image.SerializeToString,
        response_deserializer=grpc__pb2.Predictions.FromString,
        )


class GrpcServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Detect(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GrpcServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Detect': grpc.unary_unary_rpc_method_handler(
          servicer.Detect,
          request_deserializer=grpc__pb2.Image.FromString,
          response_serializer=grpc__pb2.Predictions.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Grpc', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
